version: '3.4'

services:
  catalogdb:
    image: mongo

  basketdb:
    image: redis:alpine

  discountdb:
    image: postgres

  pgadmin:
    image: dpage/pgadmin4

  portainer:
    image: portainer/portainer-ce

  mshop.catalog.api:
    image: ${DOCKER_REGISTRY-}mshopcatalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Presentation/mShop.Catalog.Api/Dockerfile

  mshop.basket.api:
    image: ${DOCKER_REGISTRY-}mshopbasketapi
    build:
      context: .
      dockerfile: src/Services/Basket/Presentation/mShop.Basket.Api/Dockerfile
  
  mshop.discount.api:
    image: ${DOCKER_REGISTRY-}mshopdiscountapi
    build:
      context: .
      dockerfile: src/Services/Discount/Presentation/mShop.Discount.Api/Dockerfile

volumes:
  mongo_data:
  portainer_data:
  postgres_data:
  pgadmin_data: