version: '3.4'

services:
  catalogdb:
    image: mongo

  mshop.catalog.api:
    image: ${DOCKER_REGISTRY-}mshopcatalogapi
    build:
      context: .
      dockerfile: src/Services/Catalog/Presentation/mShop.Catalog.Api/Dockerfile

volumes:
  mongo_data: