version: '3.4'

services:

  catalogdb:
    container_name: catalogdb
    restart: always
    ports:
        - "27017:27017" 
    volumes:
        - mongo_data:/data/db 

  basketdb:
    container_name: basketdb
    restart: always    
    ports:
        - "6379:6379"

  mshop.catalog.api:
    container_name: mshop.catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CatalogDbSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:80"

  mshop.basket.api:
    container_name: mshop.basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "BasketDbSettings:ConnectionString=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8001:80"
       